INSERT INTO BOARD (ID, NAME) VALUES (0, 'BOARD 1');
INSERT INTO BOARD (ID, NAME) VALUES (1, 'Empty board');
INSERT INTO CARD_LIST (ID, TITLE, BOARD_ID, IDX) VALUES (0, 'LIST 1', 0, 0);
INSERT INTO CARD (ID, TITLE, BOARD_ID, LIST_ID, IDX) VALUES (0, 'CARD 1', 0, 0, 0);