DROP ALL OBJECTS DELETE FILES;
CREATE TABLE BOARD
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CHECK (ID >= 0),
    CONSTRAINT BOARD_ID_UNIQUE UNIQUE (ID)
);
CREATE TABLE CARD_LIST
(
    ID       BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BOARD_ID BIGINT       NOT NULL,
    TITLE    VARCHAR(255) NOT NULL,
    IDX      INT          NOT NULL,
    CHECK (ID >= 0),
    CHECK (IDX >= 0),
    CONSTRAINT CARD_LIST_IDX_UNIQUE UNIQUE (IDX, BOARD_ID),
    CONSTRAINT CARD_LIST_ID_UNIQUE UNIQUE (ID),
    CONSTRAINT CARD_LIST_BOARD_ID_FK FOREIGN KEY (BOARD_ID) REFERENCES BOARD (ID) ON DELETE CASCADE
);
CREATE TABLE CARD
(
    ID       BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LIST_ID  BIGINT       NOT NULL,
    BOARD_ID BIGINT       NOT NULL,
    IDX      INT          NOT NULL,
    TITLE    VARCHAR(255) NOT NULL,
    CHECK (ID >= 0),
    CHECK (IDX >= 0),
    CONSTRAINT CARD_IDX_UNIQUE UNIQUE (IDX, LIST_ID),
    CONSTRAINT CARD_ID_UNIQUE UNIQUE (ID),
    CONSTRAINT CARD_CARD_LIST_ID_FK FOREIGN KEY (LIST_ID) REFERENCES CARD_LIST (ID) ON DELETE CASCADE,
    CONSTRAINT CARD_BOARD_ID_FK FOREIGN KEY (BOARD_ID) REFERENCES BOARD (ID) ON DELETE CASCADE
);