package commons;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Card {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)

    private long id;
    private long listId;
    private String title;
    private long idx;
    private long boardId;

    /**
     * Empty constructor
     */
    public Card() {
    }

    /**
     * Constructor
     *
     * @param id the Card ID
     * @param listId this Card's List ID
     * @param title the Card's title
     * @param idx the position index of card in list
     * @param boardId the Card's Board ID
     */
    public Card(long id, long listId, String title, long idx, long boardId) {
        this.id = id;
        this.listId = listId;
        this.title = title;
        this.idx = idx;
        this.boardId = boardId;
    }

    /**
     * Constructor without 'id' parameter (sets id = -1 to avoid errors)
     * - ID will be automatically generated by database
     *
     * @param listId  the Card's list's id
     * @param title   the Card's title
     * @param idx     the Card's position index in its list
     * @param boardId the Card's board's id
     */
    public Card(long listId, String title, long idx, long boardId) {
        this.id = -1;
        this.listId = listId;
        this.title = title;
        this.idx = idx;
        this.boardId = boardId;
    }

    /**
     * Getter for Card ID
     *
     * @return the Card ID
     */
    public long getId() {
        return id;
    }

    /**
     * Set the Card's id
     * @param cardId the new Card's id
     */
    public void setId(long cardId) {
        this.id = cardId;
    }

    /**
     * Get the id of the CardList the Card is in
     * @return the CardList's id
     */
    public long getListId() {
        return listId;
    }

    /**
     * Set the id of the CardList the Card is in
     * @param cardListId the id of the new CardList
     */
    public void setListId(long cardListId) {
        this.listId = cardListId;
    }

    /**
     * Get the title of the card
     * @return the card's title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Set the title of the card
     * @param cardTitle the new card's title
     */
    public void setTitle(String cardTitle) {
        this.title = cardTitle;
    }

    /**
     * Get the index of the card with respect to other cards in the same CardList
     * @return the index
     */
    public long getIdx() {
        return idx;
    }

    /**
     * Set the index of the card with respect to other cards in the same CardList
     * @param idx the new index
     */
    public void setIdx(long idx) {
        this.idx = idx;
    }

    /**
     * Get the id of the board the card is in
     * @return the board's id
     */
    public long getBoardId() {
        return boardId;
    }

    /**
     * Set the id of the board the card is in
     * @param boardId the board's id
     */
    public void setBoardId(long boardId) {
        this.boardId = boardId;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings("cyclomaticComplexity")
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Card card = (Card) o;

        if (id != card.id) return false;
        if (listId != card.listId) return false;
        if (idx != card.idx) return false;
        if (boardId != card.boardId) return false;
        return title.equals(card.title);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return "Card{" + "id='" + id + '\'' + ", cardListId='" + listId + '\'' + ", title='" +
            title + '\'' + ", nextCardId='" + idx + '\'' + ", boardId='" + boardId + '\'' + '}';
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        int result = (int) (id ^ (id >>> 32));
        result = 31 * result + (int) (listId ^ (listId >>> 32));
        result = 31 * result + title.hashCode();
        result = 31 * result + (int) (idx ^ (idx >>> 32));
        result = 31 * result + (int) (boardId ^ (boardId >>> 32));
        return result;
    }
}
